#!/usr/bin/env bash

set -e

HOST_ENTRY="192.168.1.2  vault"
LOCATION_ON_VAULT="/mnt/user/syncthing/shared_configs"

echo "Installing necessary packages and programs\n"
yay -S `cat packages_to_install`

echo "Copying sensitive files from Vault\n"
sudo echo ${HOST_ENTRY} >> /etc/hosts
scp -r root@vault:${LOCATION_ON_VAULT} .
mv shared_configs private_sync

echo "Creating a pinentry-mac link so I don't have to change configs for unix\n"
sudo ln -s /usr/bin/pinentry-gnome3 /usr/local/bin/pinentry-mac

read -n 1 -r -s -p $'If you want to overwrite existing config files you should manually delete them now.\nPress enter to continue...\n'
echo "Running dotbot to link config files\n"
./dotbot_link