#!/usr/bin/env sh

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -x polybar >/dev/null; do sleep 1; done

for m in $(polybar --list-monitors | cut -d":" -f1); do
	WIRELESS=$(ls /sys/class/net/ | grep ^wl | awk 'NR==1{print $1}') MONITOR=$m polybar -c ~/.config/polybar/config_`hostname` --reload mainbar-i3 &
done

# Old stuff
#polybar `hostname`-top -c ~/.config/polybar/config_`hostname` &
#polybar `hostname`-bottom -c ~/.config/polybar/config_`hostname` &
