#!/bin/sh

# Executes only if pywal is installed
if [ -f /usr/bin/wal ] 
then
	wal -c
	wal -i $CONFIG/wallpaper -a $TERM_ALPHA -q -o wal-vtop
	update_termite
	qutebrowser_reload.py
	betterlockscreen -u $CONFIG/wallpaper -b 0.5
fi
exit 0
